 version: 2.1
 
 jobs:
   build_arch_iso:
     # Use a machine executor to get a full VM. This is required to
     # run privileged Docker containers, which mkarchiso needs.
     machine:
       image: ubuntu-2204:current
     resource_class: large # Building an ISO is resource-intensive
 
     steps:
       - checkout
 
       # Each item in a 'steps' list starts with a hyphen and a space.
       - run:
           # 'name' and 'command' are keys indented two spaces under 'run'.
           name: Build Docker image for Arch ISO build
           command: |
             docker build -t archiso-builder .
 
       - run:
           name: Build the ISO inside a Privileged Docker Container
           command: |
             mkdir -p out
             # The --privileged flag is the critical part that solves the 'mount' error.
             docker run --rm --privileged \
               -v $(pwd):/home/builder/workspace \
               -w /home/builder/workspace \
               archiso-builder \
              bash -c "sudo mv yay / && sudo mkarchiso -v -w /tmp/archiso-work -o out ."
 
       - store_artifacts:
           # 'path' and 'destination' are indented under 'store_artifacts'.
           path: out
           destination: archlinux-custom-iso
 
 workflows:
   version: 2
   build-iso:
     jobs:
       - build_arch_iso:
           filters:
             branches:
               only:
                 - main
