#!/usr/bin/env bash
set -euo pipefail

chroot_bash() {
  HOME=/home/$USER \
    arch-chroot -u $USER /mnt/ \
    env CHROOT_INSTALL=1 \
    USER_NAME="$(<user_full_name.txt)" \
    USER_EMAIL="$(<user_email_address.txt)" \
    USER="$USER" \
    HOME="/home/$USER" \
    REPO="$(<installer_repo.txt)" \
    REF="$(<installer_ref.txt)" \
    /bin/bash "$@"
}

catch_errors() {
  echo -e "\n\e[31mInstallation failed!\e[0m"
  echo
  echo "This command halted with exit code $?:"
  echo "$BASH_COMMAND"

  if gum confirm "Retry installation?"; then
    ./.automated_script.sh
  else
    echo "You can retry later by running: ./.automated_script.sh"
  fi
}

trap catch_errors ERR

if [[ $(tty) == "/dev/tty1" ]]; then
  # Configurator for user information, disk selection, and wifi configuration
  ./configurator

  # Get username from installer config for reliable error recovery
  USER="$(jq -r '.users[0].username' user_credentials.json)"

  # Install using files generated by the ./configurator
  archinstall \
    --config user_configuration.json \
    --creds user_credentials.json \
    --silent

  # No need to ask for sudo during the installation (omarchy itself responsible for removing after install)
  mkdir -p /mnt/etc/sudoers.d
  cat >/mnt/etc/sudoers.d/99-omarchy-installer <<EOF
root ALL=(ALL:ALL) NOPASSWD: ALL
%wheel ALL=(ALL:ALL) NOPASSWD: ALL
$USER ALL=(ALL:ALL) NOPASSWD: ALL
EOF
  chmod 440 /mnt/etc/sudoers.d/99-omarchy-installer

  # Run Omarchy web installer
  INSTALL_URL=$(cat installer_url.txt 2>/dev/null || echo "https://raw.githubusercontent.com/Coding4Hours/dotfiles/refs/heads/main/install.sh")
  chroot_bash -lc "echo curl -fsSL $INSTALL_URL | bash || bash"
fi
